image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/*.jar
    expire_in: 1 week

unit-test:
  stage: test
  script:
    - ./gradlew test

integration-test:
  stage: test
  script:
    - ./gradlew integrationTest
  only:
    - tags