server:
  port: 9999

spring:
  application:
    name: ${application.name}
  boot:
    admin:
      client:
        url: https://fairie-admin.herokuapp.com/
        username: client
        password: client123
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://108.179.193.160:3306/auttom57_database_partypay
    username: auttom57_biel
    password: gabriel_g1337
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: ${application.name}
    version: ${application.version}

partypay:
  jwt:
    secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
    expiration: 86400000
