server:
  port: 9999

spring:
  profiles:
    active: des

application:
  name: ${project.name} #PartyPay Api
  description: ${project.description} #Api do Partypay
  version: ${project.version} #0.0.6
  artifactid: ${project.artifactId} #partypay




